name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature. Please describe your idea below.
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What use case does it address?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work? Include API examples if possible.
      render: typescript
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative approaches you have considered.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information.
    validations:
      required: false
